# Generated by Django 6.0.2 on 2026-02-25 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clearance', '0003_emailnotification'),
        ('departments', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClearanceStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('total_sessions', models.IntegerField(default=0)),
                ('completed_sessions', models.IntegerField(default=0)),
                ('in_progress_sessions', models.IntegerField(default=0)),
                ('blocked_sessions', models.IntegerField(default=0)),
                ('avg_completion_days', models.FloatField(default=0.0)),
                ('fastest_completion_days', models.FloatField(default=0.0)),
                ('slowest_completion_days', models.FloatField(default=0.0)),
                ('total_departments', models.IntegerField(default=0)),
                ('active_departments', models.IntegerField(default=0)),
                ('total_students', models.IntegerField(default=0)),
                ('students_with_clearance', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'reports_statistics',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='StudentProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departments_completed', models.IntegerField(default=0)),
                ('total_departments', models.IntegerField(default=0)),
                ('progress_percentage', models.FloatField(default=0.0)),
                ('started_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('days_to_complete', models.FloatField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='clearance.clearancesession')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_tracking', to='students.studentprofile')),
            ],
            options={
                'db_table': 'reports_student_progress',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='DepartmentPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_requests', models.IntegerField(default=0)),
                ('pending_requests', models.IntegerField(default=0)),
                ('approved_requests', models.IntegerField(default=0)),
                ('rejected_requests', models.IntegerField(default=0)),
                ('avg_response_days', models.FloatField(default=0.0)),
                ('avg_response_hours', models.FloatField(default=0.0)),
                ('fastest_response_hours', models.FloatField(default=0.0)),
                ('slowest_response_hours', models.FloatField(default=0.0)),
                ('approval_rate', models.FloatField(default=0.0)),
                ('rejection_rate', models.FloatField(default=0.0)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_metrics', to='departments.department')),
            ],
            options={
                'db_table': 'reports_department_performance',
                'ordering': ['-date', 'department'],
                'unique_together': {('department', 'date')},
            },
        ),
    ]
