# Generated by Django 6.0.2 on 2026-02-25 17:53

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=150)),
                ('user_role', models.CharField(blank=True, max_length=20)),
                ('action_type', models.CharField(choices=[('LOGIN', 'User Login'), ('LOGOUT', 'User Logout'), ('LOGIN_FAILED', 'Failed Login Attempt'), ('USER_CREATED', 'User Created'), ('USER_UPDATED', 'User Updated'), ('USER_DELETED', 'User Deleted'), ('SESSION_CREATED', 'Clearance Session Created'), ('CLEARANCE_APPROVED', 'Clearance Approved'), ('CLEARANCE_REJECTED', 'Clearance Rejected'), ('CLEARANCE_COMPLETED', 'Clearance Completed'), ('DEPT_CREATED', 'Department Created'), ('DEPT_UPDATED', 'Department Updated'), ('DEPT_DELETED', 'Department Deleted'), ('OFFICER_ASSIGNED', 'Officer Assigned'), ('OFFICER_REMOVED', 'Officer Removed'), ('STUDENT_CREATED', 'Student Profile Created'), ('STUDENT_UPDATED', 'Student Profile Updated'), ('STUDENT_DELETED', 'Student Profile Deleted')], max_length=30)),
                ('action_description', models.TextField()),
                ('entity_type', models.CharField(max_length=50)),
                ('entity_id', models.IntegerField(blank=True, null=True)),
                ('entity_repr', models.CharField(blank=True, max_length=255)),
                ('before_state', models.JSONField(blank=True, null=True)),
                ('after_state', models.JSONField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('request_method', models.CharField(blank=True, max_length=10)),
                ('request_path', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(default='SUCCESS', max_length=20)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'audit_logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', '-timestamp'], name='audit_logs_user_id_e11c73_idx'), models.Index(fields=['action_type', '-timestamp'], name='audit_logs_action__952b82_idx'), models.Index(fields=['entity_type', 'entity_id'], name='audit_logs_entity__d4c2e5_idx'), models.Index(fields=['timestamp'], name='audit_logs_timesta_423be6_idx')],
            },
        ),
    ]
