# Generated by Django 6.0.2 on 2026-02-15 10:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClearanceWorkflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('session_type', models.CharField(choices=[('GRADUATION', 'Graduation Clearance'), ('TRANSFER', 'Transfer Clearance'), ('INTERNSHIP', 'Internship Clearance'), ('WITHDRAWAL', 'Student Withdrawal')], max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'clearance_workflows',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ClearanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('WAIVED', 'Waived (Not Required)')], default='PENDING', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_clearances', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clearance_records', to='departments.department')),
            ],
            options={
                'db_table': 'clearance_records',
                'ordering': ['department__name'],
            },
        ),
        migrations.CreateModel(
            name='ClearanceComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clearance_comments', to=settings.AUTH_USER_MODEL)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='clearance.clearancerecord')),
            ],
            options={
                'db_table': 'clearance_comments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClearanceSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('DRAFT', 'Not Started'), ('IN_PROGRESS', 'In Progress'), ('BLOCKED', 'Blocked'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('remarks', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_clearance_sessions', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clearance_sessions', to='students.studentprofile')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='clearance.clearanceworkflow')),
            ],
            options={
                'db_table': 'clearance_sessions',
                'ordering': ['-started_at'],
            },
        ),
        migrations.AddField(
            model_name='clearancerecord',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='clearance.clearancesession'),
        ),
        migrations.CreateModel(
            name='WorkflowStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('stage_order', models.PositiveIntegerField()),
                ('description', models.TextField(blank=True)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='clearance.clearanceworkflow')),
            ],
            options={
                'db_table': 'workflow_stages',
                'ordering': ['workflow', 'stage_order'],
                'unique_together': {('workflow', 'stage_order')},
            },
        ),
        migrations.AddField(
            model_name='clearancesession',
            name='current_stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_sessions', to='clearance.workflowstage'),
        ),
        migrations.CreateModel(
            name='WorkflowStageDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_within_stage', models.PositiveIntegerField(default=0, help_text='Order within stage (0 means can be done in parallel)')),
                ('is_mandatory', models.BooleanField(default=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_stages', to='departments.department')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='clearance.workflowstage')),
            ],
            options={
                'db_table': 'workflow_stage_departments',
                'ordering': ['stage', 'order_within_stage'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='clearancerecord',
            unique_together={('session', 'department')},
        ),
        migrations.AddIndex(
            model_name='clearancesession',
            index=models.Index(fields=['student', 'status'], name='clearance_s_student_c0ef44_idx'),
        ),
        migrations.AddIndex(
            model_name='clearancesession',
            index=models.Index(fields=['status', 'current_stage'], name='clearance_s_status_520081_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='workflowstagedepartment',
            unique_together={('stage', 'department')},
        ),
    ]
