# Generated by Django 6.0.2 on 2026-02-25 13:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clearance', '0002_add_default_workflows'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('SESSION_CREATED', 'Clearance Session Created'), ('RECORD_APPROVED', 'Department Approved'), ('RECORD_REJECTED', 'Department Rejected'), ('SESSION_COMPLETED', 'Clearance Completed'), ('PENDING_REMINDER', 'Pending Clearance Reminder')], max_length=30)),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('is_sent', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_notifications', to=settings.AUTH_USER_MODEL)),
                ('record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_notifications', to='clearance.clearancerecord')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_notifications', to='clearance.clearancesession')),
            ],
            options={
                'db_table': 'email_notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', '-created_at'], name='email_notif_recipie_492dcc_idx'), models.Index(fields=['is_sent'], name='email_notif_is_sent_1651c6_idx')],
            },
        ),
    ]
