# Generated by Django 6.0.2 on 2026-02-14 17:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('department_type', models.CharField(choices=[('LIBRARY', 'Library'), ('FINANCE', 'Finance'), ('HOSTEL', 'Hostel'), ('ICT', 'ICT'), ('FACULTY', 'Faculty'), ('SPORTS', 'Sports'), ('HEALTH', 'Health Services')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('officers', models.ManyToManyField(limit_choices_to={'role': 'OFFICER'}, related_name='managed_departments', to=settings.AUTH_USER_MODEL)),
                ('parent_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_departments', to='departments.department')),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
                'db_table': 'departments',
                'indexes': [models.Index(fields=['code'], name='departments_code_9f933a_idx'), models.Index(fields=['department_type'], name='departments_departm_e45f0d_idx')],
            },
        ),
    ]
